//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ListasSarlaft.wsInspektorPrd {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSInspektorSoap", Namespace="http://tempuri.org/")]
    public partial class WSInspektor : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoadWSInspektorOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadGrantOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChekNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadContentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertEventsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSInspektor() {
            this.Url = global::ListasSarlaft.Properties.Settings.Default.ListasSarlaft_wsInspektorPrd_WSInspektor;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoadWSInspektorCompletedEventHandler LoadWSInspektorCompleted;
        
        /// <remarks/>
        public event LoadGrantCompletedEventHandler LoadGrantCompleted;
        
        /// <remarks/>
        public event ChekNameCompletedEventHandler ChekNameCompleted;
        
        /// <remarks/>
        public event LoadContentsCompletedEventHandler LoadContentsCompleted;
        
        /// <remarks/>
        public event InsertEventsCompletedEventHandler InsertEventsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadWSInspektor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoadWSInspektor(string strUsuario, string strTokenInspektor, string Numeiden, string Nombre) {
            object[] results = this.Invoke("LoadWSInspektor", new object[] {
                        strUsuario,
                        strTokenInspektor,
                        Numeiden,
                        Nombre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoadWSInspektorAsync(string strUsuario, string strTokenInspektor, string Numeiden, string Nombre) {
            this.LoadWSInspektorAsync(strUsuario, strTokenInspektor, Numeiden, Nombre, null);
        }
        
        /// <remarks/>
        public void LoadWSInspektorAsync(string strUsuario, string strTokenInspektor, string Numeiden, string Nombre, object userState) {
            if ((this.LoadWSInspektorOperationCompleted == null)) {
                this.LoadWSInspektorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadWSInspektorOperationCompleted);
            }
            this.InvokeAsync("LoadWSInspektor", new object[] {
                        strUsuario,
                        strTokenInspektor,
                        Numeiden,
                        Nombre}, this.LoadWSInspektorOperationCompleted, userState);
        }
        
        private void OnLoadWSInspektorOperationCompleted(object arg) {
            if ((this.LoadWSInspektorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadWSInspektorCompleted(this, new LoadWSInspektorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadGrant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoadGrant(string strUsuario, string strTokenInspektor) {
            object[] results = this.Invoke("LoadGrant", new object[] {
                        strUsuario,
                        strTokenInspektor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoadGrantAsync(string strUsuario, string strTokenInspektor) {
            this.LoadGrantAsync(strUsuario, strTokenInspektor, null);
        }
        
        /// <remarks/>
        public void LoadGrantAsync(string strUsuario, string strTokenInspektor, object userState) {
            if ((this.LoadGrantOperationCompleted == null)) {
                this.LoadGrantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadGrantOperationCompleted);
            }
            this.InvokeAsync("LoadGrant", new object[] {
                        strUsuario,
                        strTokenInspektor}, this.LoadGrantOperationCompleted, userState);
        }
        
        private void OnLoadGrantOperationCompleted(object arg) {
            if ((this.LoadGrantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadGrantCompleted(this, new LoadGrantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChekName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChekName(string strUsuario, string strTokenInspektor, string srtNumeIden) {
            object[] results = this.Invoke("ChekName", new object[] {
                        strUsuario,
                        strTokenInspektor,
                        srtNumeIden});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChekNameAsync(string strUsuario, string strTokenInspektor, string srtNumeIden) {
            this.ChekNameAsync(strUsuario, strTokenInspektor, srtNumeIden, null);
        }
        
        /// <remarks/>
        public void ChekNameAsync(string strUsuario, string strTokenInspektor, string srtNumeIden, object userState) {
            if ((this.ChekNameOperationCompleted == null)) {
                this.ChekNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChekNameOperationCompleted);
            }
            this.InvokeAsync("ChekName", new object[] {
                        strUsuario,
                        strTokenInspektor,
                        srtNumeIden}, this.ChekNameOperationCompleted, userState);
        }
        
        private void OnChekNameOperationCompleted(object arg) {
            if ((this.ChekNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChekNameCompleted(this, new ChekNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadContents", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoadContents(string strUsuario, string strTokenInspektor, string strType) {
            object[] results = this.Invoke("LoadContents", new object[] {
                        strUsuario,
                        strTokenInspektor,
                        strType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoadContentsAsync(string strUsuario, string strTokenInspektor, string strType) {
            this.LoadContentsAsync(strUsuario, strTokenInspektor, strType, null);
        }
        
        /// <remarks/>
        public void LoadContentsAsync(string strUsuario, string strTokenInspektor, string strType, object userState) {
            if ((this.LoadContentsOperationCompleted == null)) {
                this.LoadContentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadContentsOperationCompleted);
            }
            this.InvokeAsync("LoadContents", new object[] {
                        strUsuario,
                        strTokenInspektor,
                        strType}, this.LoadContentsOperationCompleted, userState);
        }
        
        private void OnLoadContentsOperationCompleted(object arg) {
            if ((this.LoadContentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadContentsCompleted(this, new LoadContentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertEvents", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertEvents(string strUsuario, string strTokenInspektor, cEvento evento) {
            object[] results = this.Invoke("InsertEvents", new object[] {
                        strUsuario,
                        strTokenInspektor,
                        evento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertEventsAsync(string strUsuario, string strTokenInspektor, cEvento evento) {
            this.InsertEventsAsync(strUsuario, strTokenInspektor, evento, null);
        }
        
        /// <remarks/>
        public void InsertEventsAsync(string strUsuario, string strTokenInspektor, cEvento evento, object userState) {
            if ((this.InsertEventsOperationCompleted == null)) {
                this.InsertEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertEventsOperationCompleted);
            }
            this.InvokeAsync("InsertEvents", new object[] {
                        strUsuario,
                        strTokenInspektor,
                        evento}, this.InsertEventsOperationCompleted, userState);
        }
        
        private void OnInsertEventsOperationCompleted(object arg) {
            if ((this.InsertEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertEventsCompleted(this, new InsertEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class cEvento {
        
        private string tituloField;
        
        private string fechaTransaccionField;
        
        private double montoEstimadoField;
        
        private string identificacionField;
        
        private string observacionesField;
        
        private string usuarioField;
        
        private int tipoOperacionField;
        
        private int estadoOperacionField;
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string FechaTransaccion {
            get {
                return this.fechaTransaccionField;
            }
            set {
                this.fechaTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public double MontoEstimado {
            get {
                return this.montoEstimadoField;
            }
            set {
                this.montoEstimadoField = value;
            }
        }
        
        /// <remarks/>
        public string Identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public int TipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
        
        /// <remarks/>
        public int EstadoOperacion {
            get {
                return this.estadoOperacionField;
            }
            set {
                this.estadoOperacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoadWSInspektorCompletedEventHandler(object sender, LoadWSInspektorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadWSInspektorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadWSInspektorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoadGrantCompletedEventHandler(object sender, LoadGrantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadGrantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadGrantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ChekNameCompletedEventHandler(object sender, ChekNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChekNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChekNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoadContentsCompletedEventHandler(object sender, LoadContentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadContentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadContentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InsertEventsCompletedEventHandler(object sender, InsertEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591